import type { Category } from "@/types/lesson";

/** Build up to `count` unique strings using a generator; avoids duplicates. */
function uniqueStrings(count: number, gen: (i: number) => string): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (let i = 0; i < 500 && out.length < count; i++) {
    const s = gen(i);
    if (!seen.has(s)) {
      seen.add(s);
      out.push(s);
    }
  }
  return out;
}

const workplaceVerbs = [
  "request a deadline extension",
  "ask for clearer priorities",
  "push back politely on scope creep",
  "give constructive feedback upward",
  "decline a meeting you don’t need",
  "follow up after a tense email thread",
  "negotiate workload after a reorg",
  "clarify expectations for a performance review",
  "ask for mentorship time with a senior leader",
  "explain a delay without making excuses",
  "coordinate async across time zones",
  "reset norms after a toxic meeting habit",
  "propose a shorter meeting agenda",
  "document decisions after a call",
  "escalate a blocker with data",
  "share credit in a team update",
  "recover after interrupting someone",
  "set boundaries around after-hours pings",
  "translate vague feedback into next steps",
  "ask for a written summary of verbal agreements",
  "handle a coworker taking credit for your work",
  "navigate a disagreement with your manager",
  "onboard a contractor quickly",
  "translate a technical issue for non-technical stakeholders",
  "prepare a concise weekly status update",
  "respond to an unrealistic estimate request",
  "ask for resources without sounding entitled",
  "repair trust after missing a commitment",
  "run a retro that actually changes habits",
  "say no to a low-impact project",
  "ask for a promotion conversation",
  "handle a surprise public question in a standup",
  "calm a heated Slack thread",
  "translate KPI changes for your team",
  "present bad news with a plan",
  "ask for a quieter workspace accommodation",
  "handle a micromanager diplomatically",
  "delegate without sounding dismissive",
  "recover when you forgot someone’s name",
  "clarify ownership when two teams overlap",
  "negotiate vacation during a busy season",
  "respond when your idea is shot down publicly",
  "ask for a raise with evidence",
  "handle a rumor about layoffs",
  "give peer feedback that’s honest and kind",
  "translate leadership jargon into plain English",
  "close a loop on an old email thread",
  "ask for help without sounding incompetent",
  "set expectations for a cross-team dependency",
  "wrap up a project with a lessons-learned note",
];

const travelContexts = [
  "at the airport",
  "at a train station",
  "in a taxi",
  "at hotel check-in",
  "at a rental car counter",
  "at a busy tourist attraction",
  "in a pharmacy abroad",
  "at a restaurant with dietary restrictions",
  "when your luggage is delayed",
  "when your flight is cancelled",
  "when you need to change money",
  "when you’re lost without data",
  "when you need directions politely",
  "when you must dispute a charge",
  "when you’re asking for a quieter room",
  "when you’re extending your stay",
  "when you’re asking about local etiquette",
  "when you’re reporting a lost item",
  "when you’re asking about public transit passes",
  "when you’re booking a last-minute ticket",
  "when you’re asking for a refund politely",
  "when you’re dealing with a gate change",
  "when you’re asking about baggage limits",
  "when you’re requesting a wheelchair assistance",
  "when you’re asking about tipping norms",
  "when you’re asking for a recommendation nearby",
  "when you’re handling a noisy neighbor in a hostel",
  "when you’re asking about safety at night",
  "when you’re asking about local scams to avoid",
  "when you’re asking for a copy of a receipt",
  "when you’re asking about weather contingencies",
  "when you’re asking about SIM card options",
  "when you’re asking about museum hours",
  "when you’re asking about vegetarian options",
  "when you’re asking about tap water safety",
  "when you’re asking about laundry services",
  "when you’re asking about early check-in",
  "when you’re asking about airport Wi‑Fi",
  "when you’re asking about ride-share pickup zones",
  "when you’re asking about border questions calmly",
  "when you’re asking about travel insurance coverage",
  "when you’re asking about rebooking options",
  "when you’re asking about local emergency numbers",
  "when you’re asking about child seats in cars",
  "when you’re asking about pet policies",
  "when you’re asking about accessibility ramps",
  "when you’re asking about tour cancellations",
  "when you’re asking about bike rentals",
  "when you’re asking about hiking trail conditions",
  "when you’re asking about festival tickets",
];

const shoppingMoments = [
  "returning an item without a receipt",
  "asking for a price match",
  "handling a pushy salesperson",
  "asking for a different size in the back",
  "checking warranty details",
  "asking about return windows",
  "splitting payment across two cards",
  "asking for a gift receipt",
  "asking about product ingredients",
  "asking about delivery dates",
  "asking about restocking timelines",
  "asking for a discount on a floor model",
  "asking about loyalty points",
  "asking about exchange policies",
  "asking about bundle deals",
  "asking about installation services",
  "asking about pickup options",
  "asking about subscription cancellation",
  "asking about sizing charts online vs in-store",
  "asking about rain checks on a sale item",
  "asking about damaged packaging",
  "asking about demo units",
  "asking about student discounts",
  "asking about senior discounts",
  "asking about military discounts",
  "asking about tax-free shopping",
  "asking about layaway plans",
  "asking about credit card fees",
  "asking about extended warranties",
  "asking about battery recycling",
  "asking about trade-in values",
  "asking about open-box pricing",
  "asking about coupon stacking",
  "asking about price adjustments after a sale",
  "asking about curbside pickup timing",
  "asking about substitutions in an order",
  "asking about freshness guarantees",
  "asking about allergen labeling",
  "asking about bulk pricing",
  "asking about rain checks when sold out",
  "asking about gift wrapping",
  "asking about store credit vs refund",
  "asking about defective electronics",
  "asking about missing parts in a kit",
  "asking about assembly help",
  "asking about return shipping labels",
  "asking about price protection",
  "asking about membership perks",
  "asking about store closing times",
  "asking about parking validation",
];

const socialMoments = [
  "starting a conversation at a party",
  "declining an invitation politely",
  "setting boundaries with a chatty coworker",
  "making small talk at a networking event",
  "apologizing sincerely after being late",
  "asking someone to repeat themselves kindly",
  "giving a compliment without sounding awkward",
  "accepting a compliment gracefully",
  "ending a conversation politely",
  "asking to join a table at a café",
  "offering help to a new neighbor",
  "navigating a sensitive political topic",
  "asking for privacy politely",
  "inviting someone to hang out without pressure",
  "following up after meeting someone once",
  "asking someone to lower their voice",
  "handling a friend who cancels often",
  "asking for advice without oversharing",
  "supporting a friend who is job searching",
  "declining money someone insists on lending",
  "navigating a group split on the bill",
  "asking someone to stop interrupting",
  "repairing a friendship after a misunderstanding",
  "asking for space in a relationship",
  "congratulating someone you’re jealous of",
  "responding to unsolicited advice",
  "asking to reschedule plans respectfully",
  "hosting guests when you’re low energy",
  "asking someone to remove shoes at the door",
  "navigating a noisy roommate conversation",
  "asking a neighbor to move a parked car",
  "responding to gossip diplomatically",
  "asking someone to stop texting late at night",
  "introducing two friends who should meet",
  "leaving a group chat gracefully",
  "asking for a plus-one politely",
  "navigating a wedding RSVP conflict",
  "giving feedback on a sensitive topic",
  "asking for help moving apartments",
  "responding when someone overshares",
  "asking someone to stop borrowing items",
  "navigating a friend who talks over you",
  "asking for quiet during a remote call",
  "declining a MLM pitch politely",
  "responding to a backhanded compliment",
  "asking someone to stop vaping nearby",
  "navigating a friend who asks for money",
  "asking for a recommendation letter",
  "thanking someone for a thoughtful gift",
  "closing a conversation when you’re in a hurry",
];

const healthcareMoments = [
  "describing symptoms to a nurse",
  "asking how to take a new medication",
  "requesting a prescription refill",
  "asking about side effects calmly",
  "making a doctor’s appointment on the phone",
  "asking about wait times in the ER",
  "asking for an interpreter",
  "asking about insurance coverage",
  "asking for a second opinion politely",
  "asking about lab results timing",
  "asking about vaccination scheduling",
  "asking about allergy testing",
  "asking about imaging prep instructions",
  "asking about follow-up care",
  "asking about telehealth options",
  "asking about privacy of medical records",
  "asking about payment plans",
  "asking about urgent care vs ER",
  "asking about travel vaccines",
  "asking about mental health referrals",
  "asking about physical therapy exercises",
  "asking about dietary restrictions before surgery",
  "asking about pain management options",
  "asking about pediatric dosing",
  "asking about pharmacy hours",
  "asking about generic vs brand medication",
  "asking about drug interactions",
  "asking about medical notes for work",
  "asking about specialist referrals",
  "asking about home care services",
  "asking about medical equipment rental",
  "asking about sleep study scheduling",
  "asking about glucose monitoring",
  "asking about prenatal vitamins",
  "asking about postpartum support",
  "asking about physical accessibility at a clinic",
  "asking about mask policies politely",
  "asking about billing codes",
  "asking about copay estimates",
  "asking about prior authorization",
  "asking about HIPAA basics",
  "asking about lab draw fasting",
  "asking about wound care steps",
  "asking about crutches sizing",
  "asking about physical therapy frequency",
  "asking about mental health crisis lines",
  "asking about smoking cessation resources",
  "asking about nutritionist referrals",
  "asking about hearing test scheduling",
  "asking about vision exam frequency",
];

const cultureMoments = [
  "explaining Thanksgiving traditions",
  "explaining tipping culture in the US",
  "explaining small talk norms",
  "explaining personal space expectations",
  "explaining punctuality norms",
  "explaining how to address teachers vs bosses",
  "explaining sports small talk at work",
  "explaining potluck etiquette",
  "explaining housewarming gifts",
  "explaining baby shower customs",
  "explaining wedding registry norms",
  "explaining RSVP expectations",
  "explaining casual Friday dress codes",
  "explaining drive-thru ordering flow",
  "explaining tailgating culture",
  "explaining Black Friday shopping norms",
  "explaining yard sale bargaining",
  "explaining HOA norms in suburbs",
  "explaining Halloween etiquette for kids",
  "explaining trick-or-treating safety norms",
  "explaining school spirit weeks",
  "explaining prom culture lightly",
  "explaining summer camp expectations",
  "explaining road trip etiquette",
  "explaining national park leave-no-trace norms",
  "explaining coffee shop tipping",
  "explaining bar tab splitting norms",
  "explaining karaoke participation pressure",
  "explaining open houses when apartment hunting",
  "explaining lease signing norms",
  "explaining renters insurance basics",
  "explaining public transit etiquette",
  "explaining escalator stand-right norms",
  "explaining elevator small talk",
  "explaining line culture at popular restaurants",
  "explaining food truck ordering",
  "explaining farmers market small talk",
  "explaining church visitor etiquette (generic)",
  "explaining volunteering sign-up norms",
  "explaining community meeting participation",
  "explaining PTA meeting tone",
  "explaining youth sports sideline etiquette",
  "explaining gym equipment sharing norms",
  "explaining locker room small talk boundaries",
  "explaining library quiet norms",
  "explaining museum photo policies",
  "explaining national anthem etiquette at games",
  "explaining parade crowd etiquette",
  "explaining county fair food culture",
  "explaining county fair ride safety questions",
];

const interviewMoments = [
  "answering “Tell me about yourself”",
  "answering “What are your strengths?”",
  "answering “What are your weaknesses?”",
  "answering “Why this company?”",
  "answering “Where do you see yourself in five years?”",
  "answering a behavioral question with STAR",
  "asking thoughtful questions at the end",
  "handling a salary expectation question",
  "explaining a resume gap honestly",
  "explaining a job hopper concern",
  "explaining why you’re changing industries",
  "handling a brain teaser calmly",
  "handling a panel interview",
  "handling a video interview tech glitch",
  "handling a rude interviewer diplomatically",
  "discussing remote vs hybrid preferences",
  "discussing relocation honestly",
  "discussing visa sponsorship carefully",
  "discussing notice period and start date",
  "following up after an interview",
  "thanking interviewers by email",
  "negotiating an offer professionally",
  "declining an offer politely",
  "accepting an offer clearly",
  "asking about team culture without sounding naive",
  "asking about metrics for success in the role",
  "asking about onboarding timeline",
  "asking about tech stack honestly",
  "asking about performance review cycles",
  "asking about mentorship opportunities",
  "asking about cross-functional collaboration",
  "asking about on-call expectations",
  "asking about travel expectations",
  "asking about training budget",
  "asking about diversity initiatives tactfully",
  "asking about promotion paths",
  "asking about the biggest challenge for the team",
  "asking about recent company changes",
  "asking about the interviewer’s own role",
  "handling “sell me this pen” style prompts",
  "handling a take-home assignment question",
  "handling a live coding prompt under time pressure",
  "handling a conflict question with humility",
  "handling a failure question with accountability",
  "handling a leadership question without overstating",
  "handling a teamwork question with specifics",
  "handling a deadline pressure question",
  "handling a disagreement with a manager question",
  "closing the interview confidently",
  "recovering after drawing a blank",
];

const sportsMoments = [
  "explaining basic American football rules",
  "explaining basketball positions simply",
  "explaining baseball innings casually",
  "explaining soccer vs football vocabulary",
  "ordering food at a sports bar",
  "asking about TV channel options at a bar",
  "asking about seating sections at a stadium",
  "asking an usher for help finding seats",
  "asking about bag policies at a stadium",
  "asking about parking after a game",
  "joining a recreational league as a beginner",
  "asking about cleats vs turf shoes",
  "asking about hydration during summer games",
  "asking about warm-up etiquette at a gym",
  "asking about gym membership cancellation",
  "asking about personal training politely",
  "asking about pool lap swim etiquette",
  "asking about bike trail difficulty",
  "asking about hiking gear basics",
  "asking about ski rental questions",
  "asking about rink skating basics",
  "asking about golf etiquette for beginners",
  "asking about disc golf rules lightly",
  "asking about pickleball court rotation",
  "asking about tennis scoring basics",
  "asking about volleyball rotation basics",
  "asking about running group pace etiquette",
  "asking about marathon training politely",
  "asking about sportsmanship after a rough game",
  "asking about referee calls respectfully",
  "asking about fantasy football basics",
  "asking about March Madness brackets casually",
  "asking about Super Bowl party expectations",
  "asking about tailgate food contributions",
  "asking about youth sports parent etiquette",
  "asking about coaching feedback politely",
  "asking about injury return-to-play questions",
  "asking about stretching before workouts",
  "asking about gym headphones norms",
  "asking about wiping down equipment",
  "asking about reserving a court",
  "asking about intramural team sign-ups",
  "asking about sports card collecting casually",
  "asking about local team rivalries lightly",
  "asking about stadium noise expectations",
  "asking about standing vs sitting norms",
  "asking about anthem etiquette",
  "asking about halftime show small talk",
  "asking about post-game traffic small talk",
  "asking about sports trivia without arguing",
];

export const SCENARIOS: Record<Category, string[]> = {
  workplace: uniqueStrings(50, (i) => `Workplace: You need to ${workplaceVerbs[i % workplaceVerbs.length]}.`),
  travel: uniqueStrings(50, (i) => `Travel: You’re ${travelContexts[i % travelContexts.length]} and need to communicate clearly in English.`),
  shopping: uniqueStrings(50, (i) => `Shopping: You’re ${shoppingMoments[i % shoppingMoments.length]} and want to sound polite but firm.`),
  social: uniqueStrings(50, (i) => `Social: You’re ${socialMoments[i % socialMoments.length]} and want to sound natural and respectful.`),
  healthcare: uniqueStrings(50, (i) => `Healthcare: You’re ${healthcareMoments[i % healthcareMoments.length]} and want to be clear and calm.`),
  culture: uniqueStrings(50, (i) => `Culture: You’re ${cultureMoments[i % cultureMoments.length]} to a newcomer learning American norms.`),
  job_interview: uniqueStrings(50, (i) => `Job interview: You’re ${interviewMoments[i % interviewMoments.length]} and want to sound confident and concise.`),
  sports: uniqueStrings(50, (i) => `Sports: You’re ${sportsMoments[i % sportsMoments.length]} and want friendly, natural English.`),
};

export function getRandomScenario(category: Category): string {
  const list = SCENARIOS[category];
  return list[Math.floor(Math.random() * list.length)] ?? list[0]!;
}

export function getRandomScenarioFromAny(): string {
  const categories = Object.keys(SCENARIOS) as Category[];
  const category = categories[Math.floor(Math.random() * categories.length)]!;
  return getRandomScenario(category);
}
